// Generated by delombok at Thu Sep 17 15:11:47 IST 2026
package com.urbanglide.driver.dto;

public class DriverAvailabilityRequest {
    private Boolean availability;

    public Boolean getAvailability() {
        return this.availability;
    }

    public void setAvailability(final Boolean availability) {
        this.availability = availability;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof DriverAvailabilityRequest)) return false;
        final DriverAvailabilityRequest other = (DriverAvailabilityRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$availability = this.getAvailability();
        final java.lang.Object other$availability = other.getAvailability();
        if (this$availability == null ? other$availability != null : !this$availability.equals(other$availability)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof DriverAvailabilityRequest;
    }

    @java.lang.Override
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $availability = this.getAvailability();
        result = result * PRIME + ($availability == null ? 43 : $availability.hashCode());
        return result;
    }

    @java.lang.Override
    public java.lang.String toString() {
        return "DriverAvailabilityRequest(availability=" + this.getAvailability() + ")";
    }

    public DriverAvailabilityRequest() {
    }

    public DriverAvailabilityRequest(final Boolean availability) {
        this.availability = availability;
    }
}

