// Generated by delombok at Thu Sep 17 15:11:40 IST 2026
package com.urbanglide.auth.dto;

public class LoginRequest {
    private String username;
    private String password;


    public static class LoginRequestBuilder {
        private String username;
        private String password;

        LoginRequestBuilder() {
        }

        /**
         * @return {@code this}.
         */
        public LoginRequest.LoginRequestBuilder username(final String username) {
            this.username = username;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public LoginRequest.LoginRequestBuilder password(final String password) {
            this.password = password;
            return this;
        }

        public LoginRequest build() {
            return new LoginRequest(this.username, this.password);
        }

        @java.lang.Override
        public java.lang.String toString() {
            return "LoginRequest.LoginRequestBuilder(username=" + this.username + ", password=" + this.password + ")";
        }
    }

    public static LoginRequest.LoginRequestBuilder builder() {
        return new LoginRequest.LoginRequestBuilder();
    }

    public String getUsername() {
        return this.username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setUsername(final String username) {
        this.username = username;
    }

    public void setPassword(final String password) {
        this.password = password;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof LoginRequest)) return false;
        final LoginRequest other = (LoginRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$username = this.getUsername();
        final java.lang.Object other$username = other.getUsername();
        if (this$username == null ? other$username != null : !this$username.equals(other$username)) return false;
        final java.lang.Object this$password = this.getPassword();
        final java.lang.Object other$password = other.getPassword();
        if (this$password == null ? other$password != null : !this$password.equals(other$password)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof LoginRequest;
    }

    @java.lang.Override
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $username = this.getUsername();
        result = result * PRIME + ($username == null ? 43 : $username.hashCode());
        final java.lang.Object $password = this.getPassword();
        result = result * PRIME + ($password == null ? 43 : $password.hashCode());
        return result;
    }

    @java.lang.Override
    public java.lang.String toString() {
        return "LoginRequest(username=" + this.getUsername() + ", password=" + this.getPassword() + ")";
    }

    public LoginRequest() {
    }

    public LoginRequest(final String username, final String password) {
        this.username = username;
        this.password = password;
    }
}

