// Generated by delombok at Thu Sep 17 15:12:00 IST 2026
package com.urbanglide.payment.controller;

import com.urbanglide.payment.dto.PaymentRequest;
import com.urbanglide.payment.dto.PaymentResponse;
import com.urbanglide.payment.service.PaymentService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@RequestMapping("/payments")
public class PaymentController {
    private final PaymentService paymentService;

    @PostMapping
    public ResponseEntity<PaymentResponse> processPayment(@RequestBody PaymentRequest request) {
        PaymentResponse response = paymentService.processPayment(request);
        return new ResponseEntity<>(response, HttpStatus.CREATED);
    }

    @GetMapping("/{id}")
    public ResponseEntity<PaymentResponse> getPaymentById(@PathVariable Long id) {
        return ResponseEntity.ok(paymentService.getPaymentById(id));
    }

    @GetMapping("/ride/{rideId}")
    public ResponseEntity<PaymentResponse> getPaymentByRideId(@PathVariable Long rideId) {
        return ResponseEntity.ok(paymentService.getPaymentByRideId(rideId));
    }

    @GetMapping("/rider/{riderId}")
    public ResponseEntity<List<PaymentResponse>> getPaymentsByRiderId(@PathVariable Long riderId) {
        return ResponseEntity.ok(paymentService.getPaymentsByRiderId(riderId));
    }

    @PutMapping("/{id}/refund")
    public ResponseEntity<PaymentResponse> refundPayment(@PathVariable Long id) {
        return ResponseEntity.ok(paymentService.refundPayment(id));
    }

    public PaymentController(final PaymentService paymentService) {
        this.paymentService = paymentService;
    }
}

