// Generated by delombok at Thu Sep 17 15:11:47 IST 2026
package com.urbanglide.driver.controller;

import com.urbanglide.driver.dto.*;
import com.urbanglide.driver.entity.DriverStatus;
import com.urbanglide.driver.service.DriverService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@RequestMapping("/drivers")
public class DriverController {
    private final DriverService driverService;

    @PostMapping
    public ResponseEntity<DriverDTO> createDriver(@RequestBody CreateDriverRequest request) {
        DriverDTO response = driverService.createDriver(request);
        return new ResponseEntity<>(response, HttpStatus.CREATED);
    }

    @GetMapping("/{id}")
    public ResponseEntity<DriverDTO> getDriverById(@PathVariable Long id) {
        DriverDTO response = driverService.getDriverById(id);
        return ResponseEntity.ok(response);
    }

    @GetMapping
    public ResponseEntity<List<DriverDTO>> getAllDrivers() {
        List<DriverDTO> response = driverService.getAllDrivers();
        return ResponseEntity.ok(response);
    }

    @GetMapping("/available")
    public ResponseEntity<List<DriverDTO>> getAvailableDrivers() {
        List<DriverDTO> response = driverService.getAvailableDrivers();
        return ResponseEntity.ok(response);
    }

    @PutMapping("/{id}/location")
    public ResponseEntity<DriverDTO> updateLocation(@PathVariable Long id, @RequestBody LocationUpdateRequest request) {
        DriverDTO response = driverService.updateLocation(id, request);
        return ResponseEntity.ok(response);
    }

    @PutMapping("/{id}/availability")
    public ResponseEntity<DriverDTO> updateAvailability(@PathVariable Long id, @RequestBody DriverAvailabilityRequest request) {
        DriverDTO response = driverService.updateAvailability(id, request);
        return ResponseEntity.ok(response);
    }

    @GetMapping("/nearest")
    public ResponseEntity<DriverDTO> findNearestDriver(@RequestParam double latitude, @RequestParam double longitude) {
        DriverDTO response = driverService.findNearestDriver(latitude, longitude);
        return ResponseEntity.ok(response);
    }

    @GetMapping("/nearby")
    public ResponseEntity<List<DriverDTO>> findAvailableDriversNear(@RequestParam double latitude, @RequestParam double longitude) {
        return ResponseEntity.ok(driverService.findAvailableDriversNear(latitude, longitude));
    }

    @PutMapping("/{id}/reserve")
    public ResponseEntity<java.util.Map<String, Object>> reserveDriver(@PathVariable Long id) {
        boolean reserved = driverService.reserveDriver(id);
        return ResponseEntity.ok(java.util.Map.of("reserved", reserved, "driverId", id));
    }

    @PutMapping("/{id}/status")
    public ResponseEntity<DriverDTO> updateDriverStatus(
            @PathVariable Long id,
            @RequestParam(required = false) String status,
            @RequestBody(required = false) java.util.Map<String, String> statusRequest) {
        String statusStr = status;
        if (statusStr == null && statusRequest != null) {
            statusStr = statusRequest.get("status");
        }
        if (statusStr == null || statusStr.trim().isEmpty()) {
            statusStr = "AVAILABLE"; // Safe sensible default
        }
        DriverStatus driverStatus = DriverStatus.valueOf(statusStr.trim().toUpperCase());
        DriverDTO response = driverService.updateDriverStatus(id, driverStatus);
        return ResponseEntity.ok(response);
    }

    @PutMapping("/{id}/profile")
    public ResponseEntity<DriverDTO> updateDriverProfile(
            @PathVariable Long id,
            @RequestBody com.urbanglide.driver.dto.UpdateDriverProfileRequest request) {
        DriverDTO response = driverService.updateDriverProfile(id, request);
        return ResponseEntity.ok(response);
    }

    public DriverController(final DriverService driverService) {
        this.driverService = driverService;
    }
}

