# ============================================
# UrbanGlide - Eureka Server Configuration
# ============================================

spring.application.name=EUREKA-SERVER
server.port=8761

# Eureka Server Configuration
# Do not register this server as a client with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Eureka Dashboard
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
