server.port=8086
spring.application.name=RIDE-SERVICE

# MySQL Database Config
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/urban_ride_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Thanush@752}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka Config
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true

# Actuator Endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Resilience4j Circuit Breaker Config for Driver Service
resilience4j.circuitbreaker.instances.driverService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.driverService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.driverService.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.driverService.permittedNumberOfCallsInHalfOpenState=3

# Resilience4j Circuit Breaker Config for Payment Service
resilience4j.circuitbreaker.instances.paymentService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.paymentService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentService.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.paymentService.permittedNumberOfCallsInHalfOpenState=3
