// Generated by delombok at Thu Sep 17 15:12:00 IST 2026
package com.urbanglide.payment.service;

import com.urbanglide.payment.dto.PaymentRequest;
import com.urbanglide.payment.dto.PaymentResponse;
import com.urbanglide.payment.entity.Payment;
import com.urbanglide.payment.entity.PaymentMethod;
import com.urbanglide.payment.entity.PaymentStatus;
import com.urbanglide.payment.exception.DuplicatePaymentException;
import com.urbanglide.payment.exception.InvalidPaymentStateException;
import com.urbanglide.payment.exception.PaymentNotFoundException;
import com.urbanglide.payment.exception.PaymentProcessingException;
import com.urbanglide.payment.repository.PaymentRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.List;
import java.util.Random;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
public class PaymentService {
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(PaymentService.class);
    private final PaymentRepository paymentRepository;
    private final Random random = new Random();

    @Transactional
    public PaymentResponse processPayment(PaymentRequest request) {
        log.info("Processing payment for ride {}", request.getRideId());
        if (paymentRepository.existsByRideId(request.getRideId())) {
            throw new DuplicatePaymentException("Payment already exists for ride ID: " + request.getRideId());
        }
        PaymentMethod method = PaymentMethod.CARD;
        if (request.getPaymentMethod() != null && !request.getPaymentMethod().isBlank()) {
            try {
                method = PaymentMethod.valueOf(request.getPaymentMethod().trim().toUpperCase());
            } catch (IllegalArgumentException e) {
                log.warn("Invalid payment method '{}', defaulting to CARD", request.getPaymentMethod());
                method = PaymentMethod.CARD;
            }
        }

        Payment payment = Payment.builder()
                .rideId(request.getRideId())
                .riderId(request.getRiderId())
                .amount(request.getAmount())
                .paymentMethod(method)
                .status(PaymentStatus.PENDING)
                .build();
        // Transaction ID will be set by @PrePersist on save
        payment = paymentRepository.save(payment);
        try {
            // Simulate payment processing (90% success, 10% failure)
            boolean success = random.nextInt(100) < 90;
            if (success) {
                payment.setStatus(PaymentStatus.SUCCESS);
                log.info("Payment successful for ride {}", request.getRideId());
            } else {
                payment.setStatus(PaymentStatus.FAILED);
                log.warn("Payment rejected by gateway for ride {}", request.getRideId());
            }
        } catch (Exception e) {
            payment.setStatus(PaymentStatus.FAILED);
            log.error("Error during payment processing for ride {}: {}", request.getRideId(), e.getMessage());
        }
        return convertToResponse(paymentRepository.save(payment));
    }

    @Transactional(readOnly = true)
    public PaymentResponse getPaymentById(Long id) {
        Payment payment = paymentRepository.findById(id).orElseThrow(() -> new PaymentNotFoundException("Payment not found with ID: " + id));
        return convertToResponse(payment);
    }

    @Transactional(readOnly = true)
    public PaymentResponse getPaymentByRideId(Long rideId) {
        Payment payment = paymentRepository.findByRideId(rideId).orElseThrow(() -> new PaymentNotFoundException("Payment not found for ride ID: " + rideId));
        return convertToResponse(payment);
    }

    @Transactional(readOnly = true)
    public List<PaymentResponse> getPaymentsByRiderId(Long riderId) {
        return paymentRepository.findByRiderId(riderId).stream().map(this::convertToResponse).collect(Collectors.toList());
    }

    @Transactional
    public PaymentResponse refundPayment(Long id) {
        Payment payment = paymentRepository.findById(id).orElseThrow(() -> new PaymentNotFoundException("Payment not found with ID: " + id));
        if (payment.getStatus() != PaymentStatus.SUCCESS) {
            throw new InvalidPaymentStateException("Cannot refund payment with status: " + payment.getStatus());
        }
        payment.setStatus(PaymentStatus.REFUNDED);
        log.info("Payment {} refunded successfully", id);
        return convertToResponse(paymentRepository.save(payment));
    }

    private PaymentResponse convertToResponse(Payment payment) {
        return PaymentResponse.builder().id(payment.getId()).rideId(payment.getRideId()).riderId(payment.getRiderId()).amount(payment.getAmount()).paymentMethod(payment.getPaymentMethod()).transactionId(payment.getTransactionId()).status(payment.getStatus()).createdAt(payment.getCreatedAt()).build();
    }

    public PaymentService(final PaymentRepository paymentRepository) {
        this.paymentRepository = paymentRepository;
    }
}

