name: UrbanGlide Environment
values:
  - key: baseUrl
    value: 'http://localhost:8080'
  - key: riderToken
    value: ''
  - key: driverToken
    value: ''
  - key: adminToken
    value: ''
  - key: riderId
    value: '1'
  - key: driverId
    value: '1'
  - key: rideId
    value: '1'
  - key: paymentId
    value: '1'
